[2023-12-09T12:26:10.660+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: taskflow.upload_to_gcs manual__2023-12-09T12:26:07.062414+00:00 [queued]>
[2023-12-09T12:26:10.666+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: taskflow.upload_to_gcs manual__2023-12-09T12:26:07.062414+00:00 [queued]>
[2023-12-09T12:26:10.666+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-12-09T12:26:10.675+0000] {taskinstance.py:1382} INFO - Executing <Task(LocalFilesystemToGCSOperator): upload_to_gcs> on 2023-12-09 12:26:07.062414+00:00
[2023-12-09T12:26:10.680+0000] {standard_task_runner.py:57} INFO - Started process 13914 to run task
[2023-12-09T12:26:10.683+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'taskflow', 'upload_to_gcs', 'manual__2023-12-09T12:26:07.062414+00:00', '--job-id', '74', '--raw', '--subdir', 'DAGS_FOLDER/test_decorator.py', '--cfg-path', '/tmp/tmpwgafys00']
[2023-12-09T12:26:10.686+0000] {standard_task_runner.py:85} INFO - Job 74: Subtask upload_to_gcs
[2023-12-09T12:26:10.723+0000] {task_command.py:416} INFO - Running <TaskInstance: taskflow.upload_to_gcs manual__2023-12-09T12:26:07.062414+00:00 [running]> on host 3de6e37e1218
[2023-12-09T12:26:10.793+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='taskflow' AIRFLOW_CTX_TASK_ID='upload_to_gcs' AIRFLOW_CTX_EXECUTION_DATE='2023-12-09T12:26:07.062414+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-12-09T12:26:07.062414+00:00'
[2023-12-09T12:26:10.803+0000] {connection.py:232} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2023-12-09T12:26:10.804+0000] {base.py:73} INFO - Using connection ID 'google_cloud_datastore_default' for task execution.
[2023-12-09T12:26:10.804+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/google/cloud/transfers/local_to_gcs.py", line 100, in execute
    raise ValueError(
ValueError: 'dst' parameter references filepath. Please specify directory (with trailing backslash) to upload multiple files. e.g. /path/to/directory/
[2023-12-09T12:26:10.812+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=taskflow, task_id=upload_to_gcs, execution_date=20231209T122607, start_date=20231209T122610, end_date=20231209T122610
[2023-12-09T12:26:10.822+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 74 for task upload_to_gcs ('dst' parameter references filepath. Please specify directory (with trailing backslash) to upload multiple files. e.g. /path/to/directory/; 13914)
[2023-12-09T12:26:10.860+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-12-09T12:26:10.874+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
