[2023-12-08T06:55:13.436+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: taskflow.extract manual__2023-12-08T06:55:11.374330+00:00 [queued]>
[2023-12-08T06:55:13.445+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: taskflow.extract manual__2023-12-08T06:55:11.374330+00:00 [queued]>
[2023-12-08T06:55:13.445+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 0
[2023-12-08T06:55:13.462+0000] {taskinstance.py:1382} INFO - Executing <Task(_PythonDecoratedOperator): extract> on 2023-12-08 06:55:11.374330+00:00
[2023-12-08T06:55:13.470+0000] {standard_task_runner.py:57} INFO - Started process 12869 to run task
[2023-12-08T06:55:13.476+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'taskflow', 'extract', 'manual__2023-12-08T06:55:11.374330+00:00', '--job-id', '61', '--raw', '--subdir', 'DAGS_FOLDER/test_decorator.py', '--cfg-path', '/tmp/tmpvv5lb139']
[2023-12-08T06:55:13.480+0000] {standard_task_runner.py:85} INFO - Job 61: Subtask extract
[2023-12-08T06:55:13.528+0000] {task_command.py:416} INFO - Running <TaskInstance: taskflow.extract manual__2023-12-08T06:55:11.374330+00:00 [running]> on host 3de6e37e1218
[2023-12-08T06:55:13.622+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='taskflow' AIRFLOW_CTX_TASK_ID='extract' AIRFLOW_CTX_EXECUTION_DATE='2023-12-08T06:55:11.374330+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-12-08T06:55:11.374330+00:00'
[2023-12-08T06:55:14.103+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 221, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/test_decorator.py", line 15, in extract_bitcoin_price
    return requests.get(API).json()["bitcoin"]
KeyError: 'bitcoin'
[2023-12-08T06:55:14.157+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=taskflow, task_id=extract, execution_date=20231208T065511, start_date=20231208T065513, end_date=20231208T065514
[2023-12-08T06:55:14.177+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 61 for task extract ('bitcoin'; 12869)
[2023-12-08T06:55:14.234+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-12-08T06:55:14.280+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
