[2024-01-03T14:14:46.090+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sql_example.run_bigquery_sql scheduled__2023-12-29T00:00:00+00:00 [queued]>
[2024-01-03T14:14:46.123+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sql_example.run_bigquery_sql scheduled__2023-12-29T00:00:00+00:00 [queued]>
[2024-01-03T14:14:46.124+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 0
[2024-01-03T14:14:46.150+0000] {taskinstance.py:1382} INFO - Executing <Task(BigQueryExecuteQueryOperator): run_bigquery_sql> on 2023-12-29 00:00:00+00:00
[2024-01-03T14:14:46.185+0000] {standard_task_runner.py:57} INFO - Started process 205 to run task
[2024-01-03T14:14:46.207+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'sql_example', 'run_bigquery_sql', 'scheduled__2023-12-29T00:00:00+00:00', '--job-id', '198', '--raw', '--subdir', 'DAGS_FOLDER/data_transform_BQ.py', '--cfg-path', '/tmp/tmptc4sc6b8']
[2024-01-03T14:14:46.215+0000] {standard_task_runner.py:85} INFO - Job 198: Subtask run_bigquery_sql
[2024-01-03T14:14:46.345+0000] {task_command.py:416} INFO - Running <TaskInstance: sql_example.run_bigquery_sql scheduled__2023-12-29T00:00:00+00:00 [running]> on host ae71024f9a25
[2024-01-03T14:14:46.609+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='phungquan' AIRFLOW_CTX_DAG_ID='sql_example' AIRFLOW_CTX_TASK_ID='run_bigquery_sql' AIRFLOW_CTX_EXECUTION_DATE='2023-12-29T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-12-29T00:00:00+00:00'
[2024-01-03T14:14:46.614+0000] {bigquery.py:1241} INFO - Executing: 
  -- Query for creating Dim_Supllier (SCD 1)
CREATE OR REPLACE TABLE
  `northwind-qu.Transformed_Dataset.Dim_Suppliers` AS
SELECT
  *
FROM
  `northwind-qu.test_dataset.Suppliers`;

  -- Query for creating Dim_Category(SCD 1)
CREATE OR REPLACE TABLE
  `northwind-qu.Transformed_Dataset.Dim_Categories` AS
SELECT
  *
FROM
  `northwind-qu.test_dataset.Categories`;

  -- Query for creating Dim_Products(SCD 1)
CREATE OR REPLACE TABLE
  `northwind-qu.Transformed_Dataset.Dim_Products` AS
SELECT
  t1.ProductName,
  t1.QuantityPerUnit,
  t1.UnitPrice,
  t1.UnitsInStock,
  t1.UnitsOnOrder,
  t1.ReorderLevel,
  t1.Discontinued,
  t2.CategoryName,
  t2.Description
FROM
  `northwind-qu.test_dataset.Products` t1
LEFT JOIN
  `northwind-qu.test_dataset.Categories` t2
ON
  t1.CategoryID = t2.CategoryID
-- Query for creating Dim_Date(SCD 1)
-- Continue from here
[2024-01-03T14:14:46.640+0000] {connection.py:232} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2024-01-03T14:14:46.643+0000] {base.py:73} INFO - Using connection ID 'google_cloud_default' for task execution.
[2024-01-03T14:14:46.657+0000] {logging_mixin.py:154} WARNING - /home/***/.local/lib/python3.8/site-packages/***/providers/google/cloud/hooks/bigquery.py:2108 AirflowProviderDeprecationWarning: This method is deprecated. Please use `BigQueryHook.insert_job` method.
[2024-01-03T14:14:46.659+0000] {credentials_provider.py:353} INFO - Getting connection using `google.auth.default()` since no explicit credentials are provided.
[2024-01-03T14:14:46.816+0000] {bigquery.py:1595} INFO - Inserting job ***_1704291286813710_602beda24ac1a8da4a85a20817355263
[2024-01-03T14:14:48.320+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 1249, in execute
    self.job_id = self.hook.run_query(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/google/cloud/hooks/bigquery.py", line 2241, in run_query
    job = self.insert_job(configuration=configuration, project_id=self.project_id, location=location)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/google/common/hooks/base_google.py", line 475, in inner_wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/google/cloud/hooks/bigquery.py", line 1601, in insert_job
    job_api_repr.result(timeout=timeout, retry=retry)
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/bigquery/job/query.py", line 1580, in result
    do_get_result()
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/bigquery/job/query.py", line 1570, in do_get_result
    super(QueryJob, self).result(retry=retry, timeout=timeout)
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/bigquery/job/base.py", line 922, in result
    return super(_AsyncJob, self).result(timeout=timeout, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/google/api_core/future/polling.py", line 261, in result
    raise self._exception
google.api_core.exceptions.BadRequest: 400 Not found: Table northwind-qu:test_dataset.Suppliers was not found in location asia-east1 at [3:1]

Location: asia-east1
Job ID: airflow_1704291286813710_602beda24ac1a8da4a85a20817355263

[2024-01-03T14:14:48.354+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=sql_example, task_id=run_bigquery_sql, execution_date=20231229T000000, start_date=20240103T141446, end_date=20240103T141448
[2024-01-03T14:14:48.393+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 198 for task run_bigquery_sql (400 Not found: Table northwind-qu:test_dataset.Suppliers was not found in location asia-east1 at [3:1]

Location: asia-east1
Job ID: airflow_1704291286813710_602beda24ac1a8da4a85a20817355263
; 205)
[2024-01-03T14:14:48.425+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-01-03T14:14:48.491+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
